### PR TITLE
Theme/dynamic theming

### PR DESCRIPTION
**Pull request by danconte72**
# Checklist

- [ ] My code follows the code style of this project. 
  - I've ran lint locally prior to submission.
- [ ] I successfully ran tests locally with my changes.
  - Keep mockup up-to-date for tests purpose
- [ ] I've followed the guidelines from Contributing document.
- [ ] I've updated wiki doc when necessary.
- [ ] All actions are tracked on analytics
- [ ] All expressions are translated 
- [ ] All commits Close related issue, using `Closes #ISSUE_ID`

### CODE REVIEW

**Comment by vdias38** [comment]
A lot of bugs, I add below some evidences:


|1 - wrong colors on link labels (when login button active AND not)|2 - unexpected bg colors| 3- After logout should erase custom vars|4- duplicated links|
|---|---|---|---|
|infomobi__improve_employee_experience|infomobi__improve_employee_experience|infomobi__improve_employee_experience|infomobi__improve_employee_experience_and_ion-employee_ _-bash_ _100x42|

**Comment by danconte72** [comment]
1. check default values to css vars
2. category-label component
   - update css to not apply primaryColor as bg on this element . 
3. clean vars on logout event;
4. will be handled on #312;

**Comment by vdias38** [comment]
Login raises following error
infomobi__improve_employee_experience

**Comment by vdias38** [comment]
primary color "disappear" or white...
infomobi__improve_employee_experience

**Comment by vdias38** [comment]
infomobi__improve_employee_experience

Please compare the result of this PR with current version. If theme settings are empty then style should be exactly the same as current version, it's not true at the moment.

**Comment by danconte72** [comment]
I've tested and compared the following pages
- [ ] Login
- [ ] Home
- [ ] Items List
- [ ] Item Details
- [ ] Live
- [ ] Contact List
- [ ] User Details
- [ ] Desk Details
- [ ] Desk Form
- [ ] User Form
- [ ] Comment Form
- [ ] Videos
- [ ] Login Page After logou

**Pull request closed without merging**
